version: "3.8"

services:
  backend:
    build: ./server
    container_name: backend_c
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file: ./server/.env

  frontend:
    build: ./client
    container_name: client_c
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
    stdin_open: true 
    tty: true
    depends_on:
      - backend
